Repository conda-incubator/conda-store, pull requests merged in 2023-08, with the labels that each got.

#518 Update repository URL
  README.md
  SECURITY.md
  conda-store-server/conda_store_server/alembic/versions/16f65805dc8f_split_conda_package_into_conda_package_.py
  conda-store-server/pyproject.toml
  conda-store/pyproject.toml
  docs/conf.py
  docs/contributing.md
  docs/installation.md
Labels: project: JATIC

#528 Fix default login instructions
  docs/installation.md
Labels: area: documentation 📖

#533 🔧 Create new docs env
  .readthedocs.yaml
  docs/environment-docs.yml
Labels: area: documentation 📖, status: merge ready 🚀

#500 Add trailing slash to avoid redirects
  conda-store/conda_store/api.py
  conda-store/conda_store/auth.py
  conda-store/conda_store/utils.py
  conda-store/tests/authenticated-token-tests.sh
Labels: type: bug 🐛, needs: review 👀

#523 Add a favicon to the docs and the conda-store server UI
  conda-store-server/conda_store_server/server/app.py
  conda-store-server/conda_store_server/server/static/favicon.ico
  docs/_static/images/favicon.ico
  docs/conf.py
Labels: type: enhancement 💅🏼, status: needs changes 🧱

#521 Update issue and pull request templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/general-issue.yml
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status: merge ready 🚀, project: JATIC, area: user experience 👩🏻‍💻, area: community 🌱

#536 Update release docs to reflect pyproject.toml changes
  docs/contributing.md
Labels: area: documentation 📖, status: merge ready 🚀

#537 Make the disk_usage() function work on macOS
  conda-store-server/conda_store_server/utils.py
Labels: area: api, status: in progress 🏗

#555 Fix some spelling errors in the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status: merge ready 🚀, type: maintenance 🛠, area: community 🌱
