Repository conda-incubator/conda-store, pull requests merged in 2023-10, with the labels that each got.

#550 Add a macOS worker to the CI
  .github/workflows/tests.yaml
  conda-store-server/environment-macos-dev.yaml
  conda-store-server/tests/test_app_api.py
Labels: area: testing ✅, status: in progress 🏗, needs: review 👀

#546 Better handling of pydantic error msgs
  conda-store-server/conda_store_server/schema.py
  conda-store-server/conda_store_server/server/views/api.py
Labels: type: enhancement 💅🏼, needs: review 👀, area: user experience 👩🏻‍💻

#624 :pencil2: Tone and grammar improvements to templates
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/general-issue.yml
  .github/ISSUE_TEMPLATE/new-release.md
Labels: needs: review 👀, type: maintenance 🛠

#634 ENH - Use miniforge throughout
  .github/workflows/tests.yaml
  conda-store-server/environment-dev.yaml
  conda-store-server/environment-macos-dev.yaml
  conda-store-server/environment.yaml
Labels: area: dependencies 📦, needs: review 👀, area: CI 👷🏽‍♀️

#633 :heavy_plus_sign: Add python-docker
  conda-store-server/pyproject.toml
Labels: type: bug 🐛, area: dependencies 📦, status: merge ready 🚀

#625 Dcmcand optimize docker files
  conda-store-server/Dockerfile
  conda-store/Dockerfile
Labels: status: merge ready 🚀, area: container 📦

#635 REL - 2023.10.1
  .github/ISSUE_TEMPLATE/new-release.md
  CHANGELOG.md
  conda-store-server/conda_store_server/__init__.py
  conda-store-server/hatch_build.py
  conda-store/conda_store/__init__.py
Labels: needs: review 👀, release 🏷

#636 DEV - Add build check and test release workflow
  .github/ISSUE_TEMPLATE/new-release.md
  .github/workflows/release.yaml
  README.md
  conda-store-server/README.md
  conda-store-server/conda_store_server/__init__.py
  conda-store-server/pyproject.toml
  conda-store/README.md
  conda-store/conda_store/__init__.py
Labels: area: CI 👷🏽‍♀️

#637 :bug: Add missing permissions for publishing
  .github/workflows/release.yaml
Labels: type: bug 🐛, area: CI 👷🏽‍♀️

#638 REL - 2023.10.1
  CHANGELOG.md
  conda-store-server/conda_store_server/__init__.py
  conda-store/conda_store/__init__.py
Labels: release 🏷
