Repository conda-incubator/conda-store, pull requests merged in 2023-12, with the labels that each got.

#607 Change API to be able to assign roles to namespaces
  conda-store-server/conda_store_server/alembic/versions/771180018e1b_add_v2_role_mappings.py
  conda-store-server/conda_store_server/api.py
  conda-store-server/conda_store_server/orm.py
  conda-store-server/conda_store_server/schema.py
  conda-store-server/conda_store_server/server/app.py
  conda-store-server/conda_store_server/server/auth.py
  conda-store-server/conda_store_server/server/views/api.py
  conda-store-server/tests/test_auth.py
  conda-store-server/tests/test_db_api.py
  conda-store-server/tests/test_server.py
  docs/administration.md
  tests/test_api.py
Labels: status: in progress 🏗

#685 Basic migration of conda-store (core) docs
  docusaurus-docs/README.md
  docusaurus-docs/community/contribute/contribute-code.md
  docusaurus-docs/community/contribute/contribute-docs.md
  docusaurus-docs/community/contribute/testing.md
  docusaurus-docs/community/design.md
  docusaurus-docs/community/policies/backwards-compatibility.md
  docusaurus-docs/community/policies/index.md
  docusaurus-docs/community/policies/upstream-contribution.md
  docusaurus-docs/conda-store-ui/references/storybook.md
  docusaurus-docs/conda-store/explanations/artifacts.md
  docusaurus-docs/conda-store/explanations/conda-concepts.md
  docusaurus-docs/conda-store/explanations/environments.md
  docusaurus-docs/conda-store/explanations/index.md
  docusaurus-docs/conda-store/explanations/performance.md
  docusaurus-docs/conda-store/explanations/resource-performance.md
  docusaurus-docs/conda-store/how-tos/configure-conda-store.md
  docusaurus-docs/conda-store/how-tos/install-docker.md
  docusaurus-docs/conda-store/how-tos/install-kubernetes.md
  docusaurus-docs/conda-store/how-tos/install-vagrant.md
  docusaurus-docs/conda-store/how-tos/shebang.md
  docusaurus-docs/conda-store/images/conda-store-architecture.png
  docusaurus-docs/conda-store/images/conda-store-database-architecture.png
  docusaurus-docs/conda-store/images/conda-store-entity-relationship-diagram.png
  docusaurus-docs/conda-store/images/conda-store-installation-kubernetes.webp
  docusaurus-docs/conda-store/images/conda-store-terminology.png
  docusaurus-docs/conda-store/introduction.md
  docusaurus-docs/conda-store/references/api.md
  docusaurus-docs/conda-store/references/architecture.md
  docusaurus-docs/conda-store/references/auth.md
  docusaurus-docs/conda-store/references/cli.md
  docusaurus-docs/conda-store/references/configuration-options.md
  docusaurus-docs/conda-store/references/database.md
  docusaurus-docs/conda-store/references/faq.md
  docusaurus-docs/conda-store/references/glossary.md
  docusaurus-docs/conda-store/tutorials/cli.md
  docusaurus-docs/conda-store/tutorials/install-conda-store.md
  docusaurus-docs/conda-store/tutorials/shebang.md
  docusaurus-docs/docusaurus.config.js
  docusaurus-docs/src/css/custom.css
Labels: area: documentation 📖, status: in progress 🏗, status: merge ready 🚀

#698 BUG - Remove links to changelog
  docs/contributing.md
  docusaurus-docs/community/contribute/contribute-code.md
  docusaurus-docs/community/contribute/contribute-docs.md
  docusaurus-docs/community/contribute/issues.md
  docusaurus-docs/community/contribute/testing.md
  docusaurus-docs/community/maintenance/github-conventions.md
  docusaurus-docs/community/maintenance/release.md
  docusaurus-docs/community/maintenance/reviewer-guidelines.md
  docusaurus-docs/community/maintenance/triage.md
  docusaurus-docs/conda-store/introduction.md
Labels: type: bug 🐛, area: documentation 📖, status: merge ready 🚀

#689 Place a bound on docker-py
  conda-store-server/environment-dev.yaml
  conda-store-server/environment-macos-dev.yaml
  conda-store-server/environment-windows-dev.yaml
Labels: area: dependencies 📦, status: merge ready 🚀

#701 Add brand and design guidelines
  docusaurus-docs/community/assets/conda-store-brand-guidelines.pdf
  docusaurus-docs/community/assets/logos/conda-store-logo-horizontal-lockup-black.png
  docusaurus-docs/community/assets/logos/conda-store-logo-horizontal-lockup-black.svg
  docusaurus-docs/community/assets/logos/conda-store-logo-horizontal-lockup-white.png
  docusaurus-docs/community/assets/logos/conda-store-logo-horizontal-lockup-white.svg
  docusaurus-docs/community/assets/logos/conda-store-logo-horizontal-lockup.png
  docusaurus-docs/community/assets/logos/conda-store-logo-horizontal-lockup.svg
  docusaurus-docs/community/assets/logos/conda-store-logo-vertical-lockup-black.png
  docusaurus-docs/community/assets/logos/conda-store-logo-vertical-lockup-black.svg
  docusaurus-docs/community/assets/logos/conda-store-logo-vertical-lockup-white.png
  docusaurus-docs/community/assets/logos/conda-store-logo-vertical-lockup-white.svg
  docusaurus-docs/community/assets/logos/conda-store-logo-vertical-lockup.png
  docusaurus-docs/community/assets/logos/conda-store-logo-vertical-lockup.svg
  docusaurus-docs/community/assets/logos/conda-store-symbol-only.png
  docusaurus-docs/community/assets/logos/conda-store-symbol-only.svg
  docusaurus-docs/community/design.md
Labels: area: documentation 📖, type: enhancement 💅🏼, needs: review 👀

#700 Misc clean-up docs structure
  docusaurus-docs/conda-store-ui/explanations/ui-elements.md
  docusaurus-docs/conda-store-ui/how-tos/index.md
  docusaurus-docs/conda-store-ui/how-tos/request-packages.md
  docusaurus-docs/conda-store-ui/references/release.md
  docusaurus-docs/conda-store-ui/tutorials/index.md
  docusaurus-docs/conda-store/explanations/conda-concepts.md
  docusaurus-docs/conda-store/explanations/conda-store-concepts.md
  docusaurus-docs/conda-store/references/release.md
  docusaurus-docs/jupyterlab-conda-store/release.md
  docusaurus-docs/src/css/custom.css
Labels: area: documentation 📖, type: maintenance 🛠

#704 Update npm dependencies for docusaurus v3
  docusaurus-docs/community/assets/logos/conda-store-logo-horizontal-lockup.svg
  docusaurus-docs/community/assets/logos/conda-store-logo-vertical-lockup.svg
  docusaurus-docs/community/assets/logos/conda-store-symbol-only.svg
  docusaurus-docs/conda-store-ui/tutorials/create-envs.md
  docusaurus-docs/conda-store/references/faq.md
  docusaurus-docs/package-lock.json
  docusaurus-docs/package.json
Labels: area: dependencies 📦, needs: review 👀, type: maintenance 🛠

#531 Adding build canceling (only works with compatible celery brokers redis and rabbitmq)
  conda-store-server/conda_store_server/app.py
  conda-store-server/conda_store_server/build.py
  conda-store-server/conda_store_server/schema.py
  conda-store-server/conda_store_server/server/auth.py
  conda-store-server/conda_store_server/server/templates/base.html
  conda-store-server/conda_store_server/server/templates/environment.html
  conda-store-server/conda_store_server/server/views/api.py
  conda-store-server/conda_store_server/worker/tasks.py
  conda-store-server/tests/test_server.py
  tests/test_api.py
Labels: area: api, status: merge ready 🚀, area: user experience 👩🏻‍💻

#693 Set channel priority to strict, print config info
  conda-store-server/conda_store_server/action/generate_lockfile.py
  conda-store-server/tests/test_actions.py
Labels: area: configuration, status: merge ready 🚀, area: user experience 👩🏻‍💻

#710 Use string substitution in `normalized_channel_url`
  conda-store-server/conda_store_server/conda_utils.py
  conda-store-server/tests/test_actions.py
Labels: area: dependencies 📦, status: merge ready 🚀, area: user experience 👩🏻‍💻, project: challenges

#716 Add plausible tracking snippet
  docusaurus-docs/docusaurus.config.js
Labels: area: documentation 📖
