Repository conda-incubator/conda-store, pull requests merged in 2023-09, with the labels that each got.

#558 [DOCS] Create multiple sidebars struture
  docusaurus-docs/community/contribute/contribute-core.md
  docusaurus-docs/community/contribute/contribute-docs.md
  docusaurus-docs/community/contribute/contribute-extension.md
  docusaurus-docs/community/contribute/contribute-ui.md
  docusaurus-docs/community/contribute/index.md
  docusaurus-docs/community/contribute/triage.md
  docusaurus-docs/community/design.md
  docusaurus-docs/community/github-conventions.md
  docusaurus-docs/community/governance.md
  docusaurus-docs/community/introduction.md
  docusaurus-docs/community/release.md
  docusaurus-docs/community/support.md
  docusaurus-docs/conda-store-ui/how-tos/configure-ui.md
  docusaurus-docs/conda-store-ui/how-tos/index.md
  docusaurus-docs/conda-store-ui/introduction.md
  docusaurus-docs/conda-store-ui/references/index.md
  docusaurus-docs/conda-store-ui/references/release.md
  docusaurus-docs/conda-store-ui/tutorials/authentication.md
  docusaurus-docs/conda-store-ui/tutorials/create-edit-envs.md
  docusaurus-docs/conda-store-ui/tutorials/delete-environments.md
  docusaurus-docs/conda-store-ui/tutorials/index.md
  docusaurus-docs/conda-store-ui/tutorials/install-ui.md
  docusaurus-docs/conda-store-ui/tutorials/request-packages.md
  docusaurus-docs/conda-store-ui/tutorials/version-control.md
  docusaurus-docs/conda-store/explanations/environments.md
  docusaurus-docs/conda-store/explanations/index.md
  docusaurus-docs/conda-store/explanations/resource-performance.md
  docusaurus-docs/conda-store/how-tos/configure-conda-store.md
  docusaurus-docs/conda-store/how-tos/index.md
  docusaurus-docs/conda-store/introduction.md
  docusaurus-docs/conda-store/references/api.md
  docusaurus-docs/conda-store/references/glossary.md
  docusaurus-docs/conda-store/references/index.md
  docusaurus-docs/conda-store/references/release.md
  docusaurus-docs/conda-store/references/storybook.md
  docusaurus-docs/conda-store/tutorials/cli.md
  docusaurus-docs/conda-store/tutorials/index.md
  docusaurus-docs/conda-store/tutorials/install-conda-store.md
  docusaurus-docs/conda-store/tutorials/shebang.md
  docusaurus-docs/docs/faq.md
  docusaurus-docs/docs/get-started/install-conda-store.md
  docusaurus-docs/docs/intro.md
  docusaurus-docs/docusaurus.config.js
  docusaurus-docs/jupyterlab-conda-store/install-extension.md
  docusaurus-docs/jupyterlab-conda-store/introduction.md
  docusaurus-docs/jupyterlab-conda-store/release.md
  docusaurus-docs/sidebarsCommunity.js
  docusaurus-docs/sidebarsCondaStore.js
  docusaurus-docs/sidebarsCondaStoreUI.js
  docusaurus-docs/sidebarsJupyterLab.js
  docusaurus-docs/src/pages/index.js
Labels: area: documentation 📖, type: enhancement 💅🏼, needs: review 👀

#564 Update LICENSE attribution
  LICENSE
Labels: type: maintenance 🛠, area: community 🌱

#557 Prevent traitlets from picking sys.argv during tests
  conda-store-server/tests/conftest.py
Labels: type: bug 🐛, area: testing ✅

#553 Return legacy lockfile if key is empty
  conda-store-server/conda_store_server/api.py
  conda-store-server/conda_store_server/server/views/api.py
  conda-store-server/tests/test_actions.py
Labels: area: api, status: merge ready 🚀

#565 DOC - Update homepage to include project details
  docusaurus-docs/docusaurus.config.js
  docusaurus-docs/src/pages/index.js
Labels: area: documentation 📖, type: enhancement 💅🏼, needs: review 👀, area: community 🌱

#571 Make conda-store-server test port configurable
  tests/conftest.py
  tests/test_playwright.py
Labels: area: documentation 📖

#580 MAINT - Pre release docs and improvements
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/workflows/build_docker_image.yaml
  .github/workflows/release.yaml
  conda-store-server/Dockerfile
  conda-store-server/conda_store_server/__init__.py
  conda-store-server/hatch_build.py
  conda-store-server/pyproject.toml
  conda-store/Dockerfile
  conda-store/conda_store/__init__.py
  conda-store/pyproject.toml
  docusaurus-docs/community/release.md
Labels: area: documentation 📖, status: merge ready 🚀, type: maintenance 🛠

#587 REL - `2023.9.2`
  .github/workflows/release.yaml
  conda-store-server/conda_store_server/__init__.py
  conda-store-server/pyproject.toml
  conda-store/conda_store/__init__.py
  conda-store/pyproject.toml
Labels: type: maintenance 🛠, release 🏷
