Repository conda-incubator/conda-store, pull requests merged in 2024-10, with the labels that each got.

#890 [MAINT] Add the 2024/2025 roadmap
  docusaurus-docs/community/introduction.md
  docusaurus-docs/community/roadmap.md
Labels: status: merge ready 🚀, area: community 🌱

#891 [BUG] Fix openapi.json generation workflow
  .github/workflows/generate_api_docs.yaml
Labels: area: documentation 📖, area: api, needs: review 👀, area: CI 👷🏽‍♀️

#898 REACT_APP_URL_BASENAME
  conda-store-server/conda_store_server/_internal/server/templates/conda-store-ui.html
Labels: type: enhancement 💅🏼, status: merge ready 🚀

#902 Create local conda-store dir for celery beat data files
  conda-store-server/Dockerfile
Labels: needs: review 👀, area: container 📦

#905 DEV - Extend compose to include target for local UI
  .github/ISSUE_TEMPLATE/new-release.md
  conda-store-server/Dockerfile
  docker-compose.ui.yaml
Labels: type: enhancement 💅🏼, status: merge ready 🚀, area: container 📦

#909 REL - 2024.10.1
  CHANGELOG.md
  conda-store-server/conda_store_server/__init__.py
  conda-store-server/hatch_build.py
  conda-store/conda_store/__init__.py
Labels: needs: review 👀

#910 Bump version for dev
  conda-store-server/conda_store_server/__init__.py
  conda-store/conda_store/__init__.py
Labels: needs: review 👀

#913 Wait for celery to return response to request to solve specification
  conda-store-server/conda_store_server/_internal/server/views/api.py
Labels: area: api, needs: review 👀

#908 [DOCS] Update architecture diagram + fix docs links
  docusaurus-docs/conda-store/explanations/conda-concepts.md
  docusaurus-docs/conda-store/images/conda-store-architecture.png
Labels: area: documentation 📖, needs: review 👀

#903 Respect worker log level config setting
  conda-store-server/conda_store_server/_internal/worker/app.py
Labels: type: bug 🐛, area: configuration, needs: review 👀

#919 Test improvements - part 1
  conda-store-server/README.md
  conda-store-server/pyproject.toml
  conda-store-server/tests/_internal/__init__.py
  conda-store-server/tests/_internal/action/__init__.py
  conda-store-server/tests/_internal/action/test_actions.py
  conda-store-server/tests/_internal/server/__init__.py
  conda-store-server/tests/_internal/server/views/__init__.py
  conda-store-server/tests/_internal/server/views/test_api.py
  conda-store-server/tests/_internal/server/views/test_metrics.py
  conda-store-server/tests/_internal/test_utils.py
  conda-store-server/tests/server/__init__.py
  conda-store-server/tests/server/test_auth.py
  conda-store-server/tests/test_api.py
  conda-store-server/tests/test_app.py
Labels: area: testing ✅, needs: review 👀

#923 Add coverage report to unit tests
  .github/workflows/test_conda_store_server_unit.yaml
  conda-store-server/environment-dev.yaml
  conda-store-server/pyproject.toml
Labels: area: testing ✅, area: CI 👷🏽‍♀️

#925 Move seeding tests functionality into test module
  conda-store-server/conda_store_server/_internal/testing.py
  conda-store-server/tests/conftest.py
  conda-store-server/tests/test_testing.py
Labels: area: testing ✅, needs: review 👀

#928 Remove unused _internal/client module
  conda-store-server/conda_store_server/_internal/client.py
Labels: needs: review 👀

#926 Add tests - storage + worker
  conda-store-server/tests/_internal/worker/__init__.py
  conda-store-server/tests/_internal/worker/test_app.py
  conda-store-server/tests/conftest.py
  conda-store-server/tests/test_storage.py
Labels: area: testing ✅, needs: review 👀

#933 [MAINT] Update lint tooling
  .pre-commit-config.yaml
  conda-store-server/conda_store_server/__init__.py
  conda-store-server/conda_store_server/_internal/action/download_packages.py
  conda-store-server/conda_store_server/_internal/action/generate_constructor_installer.py
  conda-store-server/conda_store_server/_internal/action/generate_lockfile.py
  conda-store-server/conda_store_server/_internal/alembic/env.py
  conda-store-server/conda_store_server/_internal/build.py
  conda-store-server/conda_store_server/_internal/dbutil.py
  conda-store-server/conda_store_server/_internal/environment.py
  conda-store-server/conda_store_server/_internal/orm.py
  conda-store-server/conda_store_server/_internal/schema.py
  conda-store-server/conda_store_server/_internal/server/__main__.py
  conda-store-server/conda_store_server/_internal/server/app.py
  conda-store-server/conda_store_server/_internal/server/views/api.py
  conda-store-server/conda_store_server/_internal/server/views/conda_store_ui.py
  conda-store-server/conda_store_server/_internal/server/views/metrics.py
  conda-store-server/conda_store_server/_internal/server/views/registry.py
  conda-store-server/conda_store_server/_internal/server/views/ui.py
  conda-store-server/conda_store_server/_internal/utils.py
  conda-store-server/conda_store_server/_internal/worker/__main__.py
  conda-store-server/conda_store_server/_internal/worker/app.py
  conda-store-server/conda_store_server/_internal/worker/tasks.py
  conda-store-server/conda_store_server/api.py
  conda-store-server/conda_store_server/app.py
  conda-store-server/conda_store_server/server/auth.py
  conda-store-server/conda_store_server/storage.py
  conda-store-server/hatch_build.py
  conda-store-server/pyproject.toml
  conda-store-server/tests/_internal/action/test_actions.py
  conda-store-server/tests/_internal/server/views/test_api.py
  conda-store-server/tests/_internal/test_utils.py
  conda-store-server/tests/_internal/worker/test_app.py
  conda-store-server/tests/conftest.py
  conda-store-server/tests/test_api.py
  conda-store-server/tests/test_app.py
  conda-store-server/tests/test_storage.py
  conda-store-server/tests/test_traitlets.py
  conda-store-server/tests/user_journeys/test_user_journeys.py
  conda-store-server/tests/user_journeys/utils/api_utils.py
Labels: type: enhancement 💅🏼, needs: review 👀, type: maintenance 🛠, area: CI 👷🏽‍♀️

#940 Make conda-store server launch uvicorn with log level
  conda-store-server/conda_store_server/_internal/server/app.py
Labels: type: bug 🐛, area: configuration, needs: review 👀, area: user experience 👩🏻‍💻
