Repository conda-incubator/conda-store, pull requests merged in 2024-01, with the labels that each got.

#709 Terminate worker tasks on SIGINT
  conda-store-server/conda_store_server/worker/tasks.py
Labels: area: configuration, status: merge ready 🚀, area: user experience 👩🏻‍💻, project: challenges

#708 Log address and port, show exception trace from `uvicorn.run`
  conda-store-server/conda_store_server/server/app.py
Labels: area: configuration, status: in progress 🏗, needs: review 👀, area: user experience 👩🏻‍💻, project: challenges

#722 Add upstream contribution policy
  docusaurus-docs/community/policies/upstream-contribution.md
Labels: area: documentation 📖, status: merge ready 🚀, area: community 🌱

#721 Pass `CONDA_OVERRIDE_CUDA` to `with_cuda` of conda-lock
  conda-store-server/conda_store_server/action/generate_lockfile.py
Labels: type: bug 🐛, area: configuration, area: dependencies 📦, status: merge ready 🚀, area: user experience 👩🏻‍💻

#687 Add backwards compatibility policy
  docusaurus-docs/community/policies/backwards-compatibility.md
Labels: area: documentation 📖, status: merge ready 🚀, area: community 🌱

#743 add how to test section to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs: review 👀

#705 Check if worker is initialized
  conda-store-server/conda_store_server/alembic/versions/0f7e23ff24ee_add_worker.py
  conda-store-server/conda_store_server/orm.py
  conda-store-server/conda_store_server/server/app.py
  conda-store-server/conda_store_server/worker/tasks.py
Labels: area: configuration, status: merge ready 🚀, area: user experience 👩🏻‍💻, project: challenges

#713 Add extended-length prefix support
  .github/workflows/tests.yaml
  conda-store-server/conda_store_server/app.py
  conda-store-server/conda_store_server/orm.py
  conda-store-server/tests/test_server.py
  docusaurus-docs/conda-store/references/faq.md
Labels: type: enhancement 💅🏼, area: configuration, status: in progress 🏗, needs: review 👀, area: user experience 👩🏻‍💻, project: challenges

#714 Generate `constructor` artifacts
  conda-store-server/conda_store_server/action/__init__.py
  conda-store-server/conda_store_server/action/generate_constructor_installer.py
  conda-store-server/conda_store_server/action/generate_lockfile.py
  conda-store-server/conda_store_server/action/utils.py
  conda-store-server/conda_store_server/alembic/versions/57cd11b949d5_add_installer.py
  conda-store-server/conda_store_server/app.py
  conda-store-server/conda_store_server/build.py
  conda-store-server/conda_store_server/orm.py
  conda-store-server/conda_store_server/schema.py
  conda-store-server/conda_store_server/server/templates/build.html
  conda-store-server/conda_store_server/server/templates/home.html
  conda-store-server/conda_store_server/server/views/api.py
  conda-store-server/conda_store_server/server/views/ui.py
  conda-store-server/conda_store_server/worker/tasks.py
  conda-store-server/environment-dev.yaml
  conda-store-server/environment-macos-dev.yaml
  conda-store-server/environment-windows-dev.yaml
  conda-store-server/environment.yaml
  conda-store-server/tests/test_actions.py
  conda-store-server/tests/test_app_api.py
  docusaurus-docs/conda-store/explanations/artifacts.md
Labels: type: enhancement 💅🏼, area: dependencies 📦, status: in progress 🏗, deliverable 📦, project: challenges

#750 REL - 2024.1.1
  CHANGELOG.md
  conda-store-server/conda_store_server/__init__.py
  conda-store-server/hatch_build.py
  conda-store/conda_store/__init__.py
Labels: release 🏷
