Repository conda-incubator/conda-store, pull requests merged in 2024-08, with the labels that each got.

#850 [MAINT] Prevent workers from trying to parse sys.argv upon intialization
  .gitignore
  conda-store-server/tests/conftest.py
Labels: type: bug 🐛, needs: discussion 💬, area: testing ✅, needs: review 👀, type: maintenance 🛠

#782 [DOC] Auto-generate openapi.json
  .github/workflows/generate_api_docs.yaml
  .gitignore
  docusaurus-docs/scripts/generate_openapi_json.py
  docusaurus-docs/static/openapi.json
Labels: area: documentation 📖, needs: discussion 💬, needs: review 👀

#838 DEV - Update dev environments
  .dockerignore
  .github/workflows/build_docker_image.yaml
  .github/workflows/conda.yml
  .github/workflows/release.yaml
  .github/workflows/test_build_docker_image.yaml
  .github/workflows/test_conda_store.yaml
  .github/workflows/test_conda_store_server_integration.yaml
  .github/workflows/test_conda_store_server_unit.yaml
  .gitignore
  .hadolint.yaml
  .pre-commit-config.yaml
  .python-version-default
  conda-store-server/Dockerfile
  conda-store-server/conda_store_server/_internal/action/generate_constructor_installer.py
  conda-store-server/conda_store_server/_internal/build.py
  conda-store-server/environment-dev.yaml
  conda-store-server/environment-macos-dev.yaml
  conda-store-server/environment-windows-dev.yaml
  conda-store-server/environment.yaml
  conda-store-server/pyproject.toml
  conda-store-server/tests/test_actions.py
  conda-store-server/tests/test_app_api.py
  conda-store/Dockerfile
  conda-store/environment.yaml
  docusaurus-docs/community/contribute/contribute-code.md
  docusaurus-docs/community/contribute/testing.md
  docusaurus-docs/conda-store-ui/how-tos/configure-ui.md
  docusaurus-docs/conda-store/how-tos/install-docker.md
  docusaurus-docs/conda-store/references/database.md
  docusaurus-docs/scripts/generate_openapi_json.py
  recipe/meta.yaml
Labels: area: dependencies 📦, status: in progress 🏗, area: CI 👷🏽‍♀️

#863 Update `openapi.json` file path in `generate_api_docs.yaml`
  .github/workflows/generate_api_docs.yaml
Labels: type: bug 🐛, needs: review 👀
