Repository conda-incubator/conda-store, pull requests merged in 2024-06, with the labels that each got.

#827 Update runtime dependencies
  conda-store-server/environment.yaml
  conda-store-server/pyproject.toml
  conda-store/environment.yaml
  conda-store/pyproject.toml
Labels: status: in progress 🏗, needs: review 👀, block-release ⛔️, type: maintenance 🛠

#832 ENH - Update workflows triggers
  .github/workflows/test_build_docker_image.yaml
  .github/workflows/test_conda_store.yaml
  .github/workflows/test_conda_store_server_integration.yaml
  .github/workflows/test_conda_store_server_unit.yaml
  .gitignore
  recipe/meta.yaml
Labels: type: enhancement 💅🏼, status: merge ready 🚀, area: CI 👷🏽‍♀️

#834 MAINT - Mock out calls to `conda-lock` for `test_solve_lockfile`
  conda-store-server/tests/test_actions.py
Labels: area: testing ✅, status: in progress 🏗, needs: review 👀, type: maintenance 🛠, needs: testing ✅, area: CI 👷🏽‍♀️

#802 MAINT - Misc improvements to repo
  .gitignore
  README.md
  conda-store-server/pyproject.toml
  conda-store/pyproject.toml
Labels: area: documentation 📖, status: merge ready 🚀, type: maintenance 🛠

#837 BUG - Fix triggers
  .github/workflows/test_build_docker_image.yaml
  .github/workflows/test_conda_store.yaml
  .github/workflows/test_conda_store_server_integration.yaml
  .github/workflows/test_conda_store_server_unit.yaml
  conda-store-server/pyproject.toml
  recipe/meta.yaml
Labels: type: bug 🐛, needs: review 👀, area: CI 👷🏽‍♀️

#774 Update metadata on landing page
  docusaurus-docs/src/pages/index.js
Labels: type: bug 🐛, area: documentation 📖, needs: review 👀

#831 DOC - Update documentation
  docusaurus-docs/community/contribute/contribute-code.md
  docusaurus-docs/conda-store/introduction.md
  docusaurus-docs/docusaurus.config.js
  docusaurus-docs/static/img/conda-store-logo-horizontal-lockup.svg
  docusaurus-docs/static/img/horizontal-logo.png
Labels: area: documentation 📖, type: enhancement 💅🏼, status: merge ready 🚀, needs: review 👀
