Repository conda-incubator/conda-store, pull requests merged in 2024-04, with the labels that each got.

#793 Add conda recipe with verification workflow
  .github/workflows/conda.yml
  recipe/meta.yaml
Labels: type: enhancement 💅🏼, area: dependencies 📦, status: merge ready 🚀, area: CI 👷🏽‍♀️

#804 Add user journey test to mark build as active
  conda-store-server/tests/user_journeys/test_data/simple_environment2.yaml
  conda-store-server/tests/user_journeys/test_user_journeys.py
  conda-store-server/tests/user_journeys/utils/api_utils.py
Labels: area: testing ✅, needs: review 👀, type: maintenance 🛠, area: CI 👷🏽‍♀️

#786 Set `CONDA_STORE_DIR` to `platformdirs.user_data_path`
  conda-store-server/conda_store_server/__init__.py
  conda-store-server/environment-dev.yaml
  conda-store-server/environment-macos-dev.yaml
  conda-store-server/environment-windows-dev.yaml
  conda-store-server/environment.yaml
  conda-store-server/pyproject.toml
  conda-store-server/tests/test_server.py
  docusaurus-docs/conda-store/references/configuration-options.md
Labels: type: enhancement 💅🏼, area: configuration, area: user experience 👩🏻‍💻, project: challenges

#773 Document user personas
  docusaurus-docs/community/design/design-system.md
  docusaurus-docs/community/design/index.md
  docusaurus-docs/community/design/user-personas.md
Labels: area: documentation 📖, needs: review 👀, area: user experience 👩🏻‍💻

#784 Update docs theme
  docusaurus-docs/src/css/custom.css
  docusaurus-docs/src/pages/index.js
Labels: area: documentation 📖, area: UI/UX design ✨, status: in progress 🏗

#790 Make conda_flags configurable
  conda-store-server/conda_store_server/app.py
  conda-store-server/conda_store_server/build.py
Labels: type: enhancement 💅🏼, area: configuration, status: in progress 🏗, needs: review 👀

#812 Add user journey test for canceling a build
  conda-store-server/tests/user_journeys/test_data/complicated_environment.yaml
  conda-store-server/tests/user_journeys/test_user_journeys.py
  conda-store-server/tests/user_journeys/utils/api_utils.py
Labels: area: testing ✅, needs: review 👀, area: CI 👷🏽‍♀️

#807 Add user journey test to retrieve a lockfile for a build
  conda-store-server/tests/user_journeys/test_user_journeys.py
  conda-store-server/tests/user_journeys/utils/api_utils.py
Labels: area: testing ✅, needs: review 👀, type: maintenance 🛠, area: CI 👷🏽‍♀️
