Repository conda-incubator/conda-store, pull requests merged in 2024-07, with the labels that each got.

#823 Add `conda config` warning docs/message; add duration log for actions
  conda-store-server/conda_store_server/_internal/action/base.py
  conda-store-server/conda_store_server/_internal/action/generate_lockfile.py
  conda-store-server/tests/test_actions.py
  docusaurus-docs/conda-store/explanations/conda-concepts.md
Labels: area: documentation 📖, type: enhancement 💅🏼, area: user experience 👩🏻‍💻

#833 MAINT - Mock out call to env solve in `test_generate_constructor_installer`
  conda-store-server/conda_store_server/_internal/build.py
  conda-store-server/conda_store_server/_internal/orm.py
  conda-store-server/conda_store_server/app.py
  conda-store-server/tests/test_actions.py
Labels: area: testing ✅, needs: review 👀, type: maintenance 🛠, area: CI 👷🏽‍♀️

#841 DEV - Simplify Docker images
  .dockerignore
  .github/workflows/build_docker_image.yaml
  .github/workflows/test_build_docker_image.yaml
  .gitignore
  .hadolint.yaml
  conda-store-server/Dockerfile
  conda-store-server/environment.yaml
  conda-store/Dockerfile
  conda-store/environment.yaml
Labels: area: dependencies 📦, needs: review 👀

#846 [MAINT] Remove deprecated docker-compose config option
  docker-compose.yaml
Labels: status: in progress 🏗, needs: review 👀, area: user experience 👩🏻‍💻, area: container 📦

#847 MAINT - Add dependabot config
  .dependabot.yml
Labels: needs: review 👀, type: maintenance 🛠

#844 DEV - Set a canonical default Python version (3.12)
  .github/workflows/build_docker_image.yaml
  .github/workflows/release.yaml
  .github/workflows/test_build_docker_image.yaml
  .github/workflows/test_conda_store.yaml
  .github/workflows/test_conda_store_server_integration.yaml
  .github/workflows/test_conda_store_server_unit.yaml
  .pre-commit-config.yaml
  .python-version-default
  conda-store-server/Dockerfile
  conda-store-server/environment-dev.yaml
  conda-store/Dockerfile
  recipe/meta.yaml
Labels: area: dependencies 📦, needs: review 👀, type: maintenance 🛠

#726 Update conda-store explanations
  docusaurus-docs/conda-store/explanations/artifacts.md
  docusaurus-docs/conda-store/explanations/conda-concepts.md
  docusaurus-docs/conda-store/explanations/conda-store-concepts.md
  docusaurus-docs/conda-store/explanations/performance.md
Labels: area: documentation 📖, type: enhancement 💅🏼, needs: review 👀

#822 Build docker images for arm (aarch64)
  .github/workflows/build_docker_image.yaml
  .github/workflows/test_build_docker_image.yaml
Labels: needs: discussion 💬, status: stale 🥖

#840 restart workers after executing 10 tasks to mitigate memory leaks
  conda-store-server/conda_store_server/_internal/worker/app.py
Labels: needs: discussion 💬, status: in progress 🏗, impact: high 🟥, area: user experience 👩🏻‍💻, type: maintenance 🛠, needs: testing ✅
