Repository conda-incubator/conda-store, pull requests merged in 2024-09, with the labels that each got.

#864 [ENH] Allow fetching of arbitrary user environments
  conda-store-server/conda_store_server/_internal/environment.py
  conda-store-server/conda_store_server/_internal/orm.py
  conda-store-server/conda_store_server/_internal/schema.py
  conda-store-server/conda_store_server/_internal/server/views/api.py
  conda-store-server/conda_store_server/_internal/utils.py
  conda-store-server/conda_store_server/api.py
  conda-store-server/conda_store_server/server/auth.py
  conda-store-server/pyproject.toml
  conda-store-server/tests/test_db_api.py
  conda-store-server/tests/test_server.py
  conda-store/pyproject.toml
  docusaurus-docs/static/openapi.json
Labels: type: enhancement 💅🏼, area: api, status: in progress 🏗, needs: review 👀

#872 DEV - Update conda-store build hook
  conda-store-server/conda_store_server/_internal/server/templates/conda-store-ui.html
  conda-store-server/conda_store_server/_internal/server/templates/navigation.html
  conda-store-server/hatch_build.py
  conda-store-server/pyproject.toml
  conda-store/pyproject.toml
  docusaurus-docs/static/openapi.json
  tests/assets/conda_store_config.py
Labels: type: enhancement 💅🏼, area: dependencies 📦, block-release ⛔️, area: javascript

#879 [MAINT] Make github workflow format openapi.json
  .github/workflows/generate_api_docs.yaml
  docusaurus-docs/static/openapi.json
Labels: area: documentation 📖, area: api, type: maintenance 🛠, github_actions

#878 BUG - Fix release workflows
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/new-release.md
  .github/workflows/release.yaml
  docusaurus-docs/community/contribute/contribute-docs.md
  docusaurus-docs/community/introduction.md
  docusaurus-docs/community/maintenance/release.md
Labels: block-release ⛔️, area: CI 👷🏽‍♀️, github_actions

#880 REL - 2024.9.1
  CHANGELOG.md
  conda-store-server/conda_store_server/__init__.py
  conda-store-server/hatch_build.py
  conda-store/conda_store/__init__.py
  docusaurus-docs/static/openapi.json
Labels: needs: review 👀, release 🏷

#885 BUG - patch release workflow
  .github/workflows/release.yaml
  conda-store-server/hatch_build.py
Labels: needs: review 👀, area: CI 👷🏽‍♀️

#887 Revert "REL - 2024.9.1 (#880)"
  CHANGELOG.md
  conda-store-server/conda_store_server/__init__.py
  conda-store/conda_store/__init__.py
  docusaurus-docs/static/openapi.json
Labels: needs: review 👀, block-release ⛔️
