Repository conda-incubator/conda-store, pull requests merged in 2024-03, with the labels that each got.

#778 REL - 2024.3.1
  conda-store-server/conda_store_server/__init__.py
  conda-store-server/hatch_build.py
  conda-store/conda_store/__init__.py
Labels: release 🏷

#779 Add CHANGELOG entries for v2024.3.1
  CHANGELOG.md
Labels: release 🏷

#752 [DOC] Add JupyterLab Extension docs page
  docusaurus-docs/docusaurus.config.js
  docusaurus-docs/jupyterlab-conda-store/images/conda-store-menu-item.png
  docusaurus-docs/jupyterlab-conda-store/install-extension.md
  docusaurus-docs/jupyterlab-conda-store/introduction.md
  docusaurus-docs/jupyterlab-conda-store/introduction.mdx
Labels: area: documentation 📖, needs: review 👀

#766 Create temp REST API reference
  docusaurus-docs/conda-store/references/api.md
  docusaurus-docs/conda-store/references/api.mdx
  docusaurus-docs/static/openapi.json
  docusaurus-docs/static/rest-api.html
Labels: area: documentation 📖, needs: review 👀

#776 Add user journey for logging in and deleting shared environment
  conda-store-server/tests/user_journeys/test_user_journeys.py
  conda-store-server/tests/user_journeys/utils/api_utils.py
Labels: area: testing ✅, status: merge ready 🚀

#795 MAINT - Bump actions versions
  .github/workflows/build_docker_image.yaml
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
Labels: area: dependencies 📦, needs: review 👀, area: CI 👷🏽‍♀️

#798 MAINT - Add conda-store dependencies to pyproject.toml
  .github/workflows/tests.yaml
  conda-store-server/pyproject.toml
  conda-store/environment.yaml
  conda-store/pyproject.toml
Labels: area: dependencies 📦, needs: review 👀, type: maintenance 🛠

#797 Add user journey test to check that logs can be found for failed builds
  conda-store-server/tests/user_journeys/test_data/broken_environment.yaml
  conda-store-server/tests/user_journeys/test_user_journeys.py
  conda-store-server/tests/user_journeys/utils/api_utils.py
Labels: area: testing ✅, needs: review 👀, area: CI 👷🏽‍♀️
