Repository conda-incubator/conda-store, pull requests merged in 2024-11, with the labels that each got.

#935 Move dependencies module into conda store server module
  conda-store-server/conda_store_server/_internal/server/dependencies.py
  conda-store-server/conda_store_server/_internal/server/views/api.py
  conda-store-server/conda_store_server/_internal/server/views/conda_store_ui.py
  conda-store-server/conda_store_server/_internal/server/views/metrics.py
  conda-store-server/conda_store_server/_internal/server/views/registry.py
  conda-store-server/conda_store_server/_internal/server/views/ui.py
  conda-store-server/conda_store_server/server/auth.py
  conda-store-server/tests/_internal/server/views/test_api.py
Labels: needs: review 👀, type: maintenance 🛠

#945 Move build to worker
  conda-store-server/conda_store_server/_internal/worker/build.py
  conda-store-server/conda_store_server/_internal/worker/tasks.py
  conda-store-server/tests/_internal/worker/test_build.py
Labels: needs: review 👀, type: maintenance 🛠

#973 [BUG] Fix python version compatibility issues affecting tests
  .github/workflows/test_conda_store.yaml
  .github/workflows/test_conda_store_server_integration.yaml
  conda-store-server/conda_store_server/_internal/schema.py
  conda-store-server/environment-dev.yaml
  conda-store-server/pyproject.toml
  conda-store/pyproject.toml
  docker-compose.yaml
  docusaurus-docs/community/contribute/local-setup-labextension.md
  recipe/meta.yaml
Labels: area: dependencies 📦, area: testing ✅, status: merge ready 🚀, impact: high 🟥, type: maintenance 🛠, area: CI 👷🏽‍♀️, type: dependency update

#980 Bump dev version
  conda-store-server/conda_store_server/__init__.py
  conda-store/conda_store/__init__.py
Labels: needs: review 👀

#981 DEV - Set traitlets application version
  conda-store-server/conda_store_server/_internal/server/app.py
  conda-store-server/conda_store_server/_internal/worker/app.py
Labels: type: enhancement 💅🏼, status: merge ready 🚀, area: user experience 👩🏻‍💻

#990 MAINT - Bump base Docker image version
  conda-store-server/Dockerfile
  conda-store/Dockerfile
Labels: area: dependencies 📦, needs: review 👀, type: maintenance 🛠

#988 MAINT - Update dependabot configuration
  .dependabot.yml
Labels: area: dependencies 📦, needs: review 👀, type: maintenance 🛠

#932 Create catch-all/fallback route for UI app
  conda-store-server/conda_store_server/_internal/server/app.py
  conda-store-server/conda_store_server/_internal/server/dependencies.py
  conda-store-server/conda_store_server/_internal/server/templates/conda-store-ui.html
  conda-store-server/conda_store_server/_internal/server/views/conda_store_ui.py
  conda-store-server/tests/_internal/server/views/test_conda_store_ui.py
  docusaurus-docs/conda-store-ui/how-tos/configure-ui.md
Labels: needs: review 👀, type: maintenance 🛠

#961 Update conda-package-build causes an integrity error on conda_package_build table
  conda-store-server/conda_store_server/_internal/orm.py
  conda-store-server/tests/_internal/test_orm.py
Labels: type: bug 🐛, needs: review 👀

#985 [MAINT] Update pydantic to >=2.0
  conda-store-server/conda_store_server/_internal/action/generate_lockfile.py
  conda-store-server/conda_store_server/_internal/action/install_specification.py
  conda-store-server/conda_store_server/_internal/schema.py
  conda-store-server/conda_store_server/_internal/server/templates/setting.html
  conda-store-server/conda_store_server/_internal/server/views/api.py
  conda-store-server/conda_store_server/api.py
  conda-store-server/conda_store_server/app.py
  conda-store-server/conda_store_server/server/auth.py
  conda-store-server/pyproject.toml
  conda-store-server/tests/_internal/action/test_actions.py
  conda-store-server/tests/_internal/test_schema.py
  conda-store-server/tests/test_app.py
  recipe/meta.yaml
Labels: area: dependencies 📦, type: maintenance 🛠, needs: testing ✅, type: dependency update

#998 [MAINT] - Don't keep `_version.py` file in version control
  conda-store-server/conda_store_server/_version.py
Labels: needs: review 👀, type: maintenance 🛠

#1003 Bump dev version
  conda-store-server/conda_store_server/__init__.py
  conda-store/conda_store/__init__.py
Labels: status: merge ready 🚀
