Repository conda-incubator/conda-store, pull requests merged in 2024-02, with the labels that each got.

#738 Add support for the `editor` role
  conda-store-server/conda_store_server/api.py
  conda-store-server/conda_store_server/orm.py
  conda-store-server/conda_store_server/server/auth.py
  conda-store-server/tests/test_auth.py
  conda-store-server/tests/test_db_api.py
  docusaurus-docs/conda-store/references/auth.md
  docusaurus-docs/conda-store/references/configuration-options.md
  tests/test_api.py
Labels: type: enhancement 💅🏼, status: merge ready 🚀, area: user experience 👩🏻‍💻

#745 Add a test for parallel builds, fix race conditions due to the shared conda cache
  conda-store-server/conda_store_server/action/download_packages.py
  conda-store-server/conda_store_server/utils.py
  conda-store-server/environment-dev.yaml
  conda-store-server/environment-macos-dev.yaml
  conda-store-server/environment-windows-dev.yaml
  conda-store-server/environment.yaml
  tests/test_api.py
Labels: type: bug 🐛, type: enhancement 💅🏼, area: testing ✅, status: in progress 🏗, needs: review 👀, area: user experience 👩🏻‍💻

#760 Add user journey test
  .github/workflows/tests.yaml
  conda-store-server/pyproject.toml
  conda-store-server/tests/user_journeys/README.md
  conda-store-server/tests/user_journeys/test_data/simple_environment.yaml
  conda-store-server/tests/user_journeys/test_user_journeys.py
  conda-store-server/tests/user_journeys/utils/__init__.py
  conda-store-server/tests/user_journeys/utils/api_utils.py
  conda-store-server/tests/user_journeys/utils/time_utils.py
Labels: area: testing ✅, status: merge ready 🚀

#770 Run linter on tests and docs
  .pre-commit-config.yaml
  conda-store-server/tests/conftest.py
  conda-store-server/tests/test_actions.py
  conda-store-server/tests/test_auth.py
  conda-store-server/tests/test_db_api.py
  conda-store-server/tests/test_server.py
  conda-store-server/tests/test_usage.py
  conda-store-server/tests/user_journeys/utils/api_utils.py
  conda-store-server/tests/user_journeys/utils/time_utils.py
  tests/conftest.py
  tests/test_api.py
  tests/test_playwright.py
Labels: area: documentation 📖, area: testing ✅, status: in progress 🏗, needs: review 👀, type: maintenance 🛠

#762 [DOC] Remove duplicate image
  docusaurus-docs/conda-store-ui/images/versions-view.png
  docusaurus-docs/conda-store-ui/tutorials/version-control.md
Labels: area: documentation 📖, status: merge ready 🚀

#747 Add status `CANCELED`
  conda-store-server/conda_store_server/alembic/versions/03c839888c82_add_canceled_status.py
  conda-store-server/conda_store_server/build.py
  conda-store-server/conda_store_server/schema.py
  conda-store-server/conda_store_server/server/templates/build.html
  conda-store-server/conda_store_server/server/views/api.py
  conda-store-server/conda_store_server/worker/tasks.py
  conda-store-server/tests/user_journeys/utils/api_utils.py
  tests/test_api.py
Labels: type: enhancement 💅🏼, area: UI/UX design ✨, area: api, status: merge ready 🚀, project: JATIC, area: user experience 👩🏻‍💻, project: challenges

#765 [DOC] Document setting environment variable
  docusaurus-docs/conda-store-ui/tutorials/create-envs.md
Labels: area: documentation 📖, status: merge ready 🚀
