Repository conda-incubator/conda-store, pull requests merged in 2024-12, with the labels that each got.

#965 Setup pluggy with locking plugin
  conda-store-server/conda_store_server/_internal/action/__init__.py
  conda-store-server/conda_store_server/_internal/action/generate_lockfile.py
  conda-store-server/conda_store_server/_internal/plugins/__init__.py
  conda-store-server/conda_store_server/_internal/plugins/lock/__init__.py
  conda-store-server/conda_store_server/_internal/plugins/lock/conda_lock/__init__.py
  conda-store-server/conda_store_server/_internal/plugins/lock/conda_lock/conda_lock.py
  conda-store-server/conda_store_server/_internal/utils.py
  conda-store-server/conda_store_server/_internal/worker/build.py
  conda-store-server/conda_store_server/app.py
  conda-store-server/conda_store_server/exception.py
  conda-store-server/conda_store_server/plugins/__init__.py
  conda-store-server/conda_store_server/plugins/hookspec.py
  conda-store-server/conda_store_server/plugins/plugin_context.py
  conda-store-server/conda_store_server/plugins/plugin_manager.py
  conda-store-server/conda_store_server/plugins/types/__init__.py
  conda-store-server/conda_store_server/plugins/types/lock.py
  conda-store-server/conda_store_server/plugins/types/types.py
  conda-store-server/pyproject.toml
  conda-store-server/tests/_internal/action/test_actions.py
  conda-store-server/tests/_internal/plugins/__init__.py
  conda-store-server/tests/_internal/plugins/lock/__init__.py
  conda-store-server/tests/_internal/plugins/lock/test_conda_lock.py
  conda-store-server/tests/conftest.py
  conda-store-server/tests/plugins/__init__.py
  conda-store-server/tests/plugins/test_plugin_context.py
  conda-store-server/tests/plugins/test_plugin_manager.py
  conda-store-server/tests/test_app.py
  docusaurus-docs/conda-store/references/configuration-options.md
  recipe/meta.yaml
Labels: needs: review 👀

#1001 Remove docker build tasks
  conda-store-server/conda_store_server/_internal/action/__init__.py
  conda-store-server/conda_store_server/_internal/action/generate_conda_docker.py
  conda-store-server/conda_store_server/_internal/schema.py
  conda-store-server/conda_store_server/_internal/server/views/api.py
  conda-store-server/conda_store_server/_internal/worker/build.py
  conda-store-server/conda_store_server/_internal/worker/tasks.py
  conda-store-server/conda_store_server/api.py
  conda-store-server/conda_store_server/app.py
  conda-store-server/tests/_internal/action/test_actions.py
  conda-store-server/tests/_internal/server/views/test_api.py
  conda-store-server/tests/conftest.py
  conda-store-server/tests/test_app.py
  docusaurus-docs/conda-store/explanations/artifacts.md
  docusaurus-docs/conda-store/references/architecture.md
  docusaurus-docs/conda-store/references/configuration-options.md
  docusaurus-docs/src/pages/index.js
Labels: area: api, needs: review 👀, area: user experience 👩🏻‍💻

#1011 Fix conda_package_build "build" column type
  conda-store-server/conda_store_server/_internal/orm.py
Labels: needs: review 👀

#1006 Release helper script
  .github/ISSUE_TEMPLATE/new-release.md
  cut-release-pr.sh
Labels: needs: review 👀, type: maintenance 🛠

#1004 Don't use `quansight/conda-store` docker image
  docusaurus-docs/conda-store/how-tos/install-docker.md
  examples/docker-without-nfs/assets/conda_store_config.py
  examples/docker-without-nfs/assets/jupyterhub_config.py
  examples/docker-without-nfs/docker-compose.yaml
  examples/docker-without-nfs/dockerfiles/jupyterhub.Dockerfile
  examples/docker/assets/conda_store_config.py
  examples/docker/assets/jupyterhub_config.py
  examples/docker/docker-compose.yaml
  examples/docker/dockerfiles/jupyterhub.Dockerfile
Labels: area: documentation 📖, needs: review 👀, type: maintenance 🛠

#1015 Run unit tests on all supported python versions
  .github/workflows/test_conda_store_server_unit.yaml
Labels: area: dependencies 📦, area: testing ✅, status: merge ready 🚀

#1017 Remove upload to docker registry code snippets
  conda-store-server/conda_store_server/_internal/orm.py
  conda-store-server/conda_store_server/_internal/schema.py
  conda-store-server/conda_store_server/_internal/worker/tasks.py
  conda-store-server/conda_store_server/app.py
  conda-store-server/conda_store_server/registry.py
  docusaurus-docs/conda-store/references/configuration-options.md
  tests/assets/conda_store_config.py
Labels: type: deprecations ⛔️

#1013 Fix deprecation warnings
  conda-store-server/conda_store_server/_internal/environment.py
  conda-store-server/conda_store_server/_internal/plugins/lock/conda_lock/conda_lock.py
  conda-store-server/conda_store_server/_internal/schema.py
  conda-store-server/conda_store_server/_internal/server/views/api.py
  conda-store-server/conda_store_server/_internal/server/views/conda_store_ui.py
  conda-store-server/conda_store_server/_internal/server/views/ui.py
  conda-store-server/conda_store_server/_internal/worker/build.py
  conda-store-server/conda_store_server/app.py
  conda-store-server/conda_store_server/server/auth.py
  conda-store-server/tests/_internal/action/test_actions.py
  conda-store-server/tests/_internal/server/views/test_api.py
  conda-store-server/tests/_internal/test_schema.py
  conda-store-server/tests/conftest.py
  tests/test_api.py
Labels: needs: review 👀, type: maintenance 🛠

#1029 fix: handle None system metrics in user admin panel
  conda-store-server/conda_store_server/_internal/server/templates/user.html
Labels: type: bug 🐛, area: UI/UX design ✨

#1027 Move cut-release-pr script into tool dir
  tools/cut-release-pr.sh
Labels: needs: review 👀

#1026 Consolidate exception classes :broom:
  conda-store-server/conda_store_server/_internal/orm.py
  conda-store-server/conda_store_server/_internal/schema.py
  conda-store-server/conda_store_server/_internal/server/views/api.py
  conda-store-server/conda_store_server/_internal/utils.py
  conda-store-server/conda_store_server/_internal/worker/build.py
  conda-store-server/conda_store_server/app.py
  conda-store-server/conda_store_server/exception.py
  conda-store-server/tests/test_api.py
Labels: needs: review 👀, type: maintenance 🛠
