Repository conda-incubator/conda-store, pull requests merged in 2025-01, with the labels that each got.

#1033 Don't output db secret to logs
  conda-store-server/conda_store_server/_internal/server/app.py
Labels: type: bug 🐛, needs: review 👀

#1010 Remove redundant channel column
  .gitignore
  conda-store-server/conda_store_server/_internal/alembic/script.py.mako
  conda-store-server/conda_store_server/_internal/alembic/versions/89637f546129_remove_conda_package_build_channel.py
  conda-store-server/conda_store_server/_internal/orm.py
  conda-store-server/environment-dev.yaml
  conda-store-server/pyproject.toml
  conda-store-server/tests/_internal/alembic/__init__.py
  conda-store-server/tests/_internal/alembic/version/__init__.py
  conda-store-server/tests/_internal/alembic/version/test_89637f546129_remove_conda_package_build_channel.py
  conda-store-server/tests/_internal/test_orm.py
  conda-store-server/tests/conftest.py
  docusaurus-docs/conda-store/references/database.md
Labels: status: merge ready 🚀

#1023 Separate conda-store app instance from config
  conda-store-server/conda_store_server/_internal/orm.py
  conda-store-server/conda_store_server/_internal/plugins/lock/conda_lock/conda_lock.py
  conda-store-server/conda_store_server/_internal/server/app.py
  conda-store-server/conda_store_server/_internal/server/views/api.py
  conda-store-server/conda_store_server/_internal/server/views/ui.py
  conda-store-server/conda_store_server/_internal/worker/app.py
  conda-store-server/conda_store_server/_internal/worker/tasks.py
  conda-store-server/conda_store_server/conda_store.py
  conda-store-server/conda_store_server/conda_store_config.py
  conda-store-server/tests/_internal/action/test_actions.py
  conda-store-server/tests/_internal/plugins/lock/test_conda_lock.py
  conda-store-server/tests/_internal/worker/test_app.py
  conda-store-server/tests/conftest.py
  conda-store-server/tests/test_api.py
  conda-store-server/tests/test_conda_store.py
  conda-store-server/tests/test_conda_store_config.py
Labels: needs: review 👀

#1039 Login page without UI enabled
  conda-store-server/conda_store_server/_internal/server/templates/login.html
  conda-store-server/conda_store_server/server/auth.py
  conda-store-server/tests/conftest.py
  conda-store-server/tests/server/test_auth.py
  tests/test_playwright.py
Labels: area: testing ✅, type: maintenance 🛠

#1046 Move auth related schema to inside the auth module
  conda-store-server/conda_store_server/_internal/environment.py
  conda-store-server/conda_store_server/_internal/orm.py
  conda-store-server/conda_store_server/_internal/schema.py
  conda-store-server/conda_store_server/_internal/server/views/api.py
  conda-store-server/conda_store_server/_internal/server/views/registry.py
  conda-store-server/conda_store_server/_internal/server/views/ui.py
  conda-store-server/conda_store_server/api.py
  conda-store-server/conda_store_server/conda_store.py
  conda-store-server/conda_store_server/conda_store_config.py
  conda-store-server/conda_store_server/server/auth.py
  conda-store-server/conda_store_server/server/schema.py
  conda-store-server/tests/_internal/server/views/test_api.py
  conda-store-server/tests/server/test_auth.py
  docusaurus-docs/conda-store/references/auth.md
  tests/test_api.py
Labels: type: maintenance 🛠

#1050 Fix user-journey tests for running against non-default targets
  conda-store-server/tests/user_journeys/test_user_journeys.py
  conda-store-server/tests/user_journeys/utils/api_utils.py
Labels: area: testing ✅

#881 Sort envs returned by REST API by current build's scheduled_on time
  conda-store-server/conda_store_server/_internal/schema.py
  conda-store-server/conda_store_server/_internal/server/app.py
  conda-store-server/conda_store_server/_internal/server/dependencies.py
  conda-store-server/conda_store_server/_internal/server/pagination.py
  conda-store-server/conda_store_server/_internal/server/views/__init__.py
  conda-store-server/conda_store_server/_internal/server/views/api.py
  conda-store-server/conda_store_server/_internal/server/views/api_v2.py
  conda-store-server/pyproject.toml
  conda-store-server/tests/_internal/server/views/test_api.py
  conda-store-server/tests/conftest.py
  conda-store/conda_store/api.py
Labels: type: bug 🐛, area: api 🌐, needs: review 👀, area: user experience 👩🏻‍💻

#1056 Trim conda-store package dependencies
  conda-store/pyproject.toml
Labels: area: dependencies 📦, needs: review 👀

#1054 Ensure settings are retrieved for the right level
  conda-store-server/conda_store_server/_internal/settings.py
  conda-store-server/conda_store_server/_internal/worker/tasks.py
  conda-store-server/conda_store_server/conda_store.py
  conda-store-server/conda_store_server/conda_store_config.py
Labels: type: enhancement 💅🏼, area: configuration ⚙️, needs: review 👀, area: user experience 👩🏻‍💻

#1016 Deprecate docker registry
  conda-store-server/conda_store_server/_internal/server/app.py
  conda-store-server/conda_store_server/_internal/server/views/api.py
  conda-store-server/conda_store_server/_internal/server/views/registry.py
  conda-store-server/tests/_internal/server/views/test_api.py
  docusaurus-docs/conda-store/explanations/artifacts.md
  docusaurus-docs/conda-store/references/configuration-options.md
  examples/docker-without-nfs/assets/conda_store_config.py
  examples/docker/assets/conda_store_config.py
  examples/kubernetes/files/conda_store_config.py
  examples/ubuntu2004/templates/conda_store_config.py.j2
  tests/assets/conda_store_config.py
Labels: area: container 📦, type: deprecations ⛔️

#1018 Deprecation guide
  docusaurus-docs/community/policies/backwards-compatibility.md
Labels: area: documentation 📖, needs: review 👀, type: governance 📄

#1060 Build and release a arm64 docker image as part of the release process
  .github/workflows/release.yaml
Labels: status: merge ready 🚀, type: maintenance 🛠, area: CI 👷🏽‍♀️, area: github actions

#1063 Allow Namespace pydantic model to have a null metadata_ entry
  conda-store-server/conda_store_server/_internal/schema.py
  conda-store-server/tests/_internal/server/views/test_api.py
  conda-store-server/tests/conftest.py
Labels: type: bug 🐛, area: api 🌐, needs: review 👀, block-release ⛔️

#1066 Bump dev version
  .github/ISSUE_TEMPLATE/new-release.md
  conda-store-server/conda_store_server/__init__.py
  conda-store/conda_store/__init__.py
Labels: needs: review 👀

#1073 REL - 2025.1.2-rc1
  conda-store-server/conda_store_server/__init__.py
  conda-store/conda_store/__init__.py
Labels: release 🏷
