Repository conda-incubator/conda-store, pull requests merged in 2025-02, with the labels that each got.

#1075 [MAINT] Replace prettier with biome; fix bad pre-commit exclusion rule
  .pre-commit-config.yaml
  docusaurus-docs/babel.config.js
  docusaurus-docs/docusaurus.config.js
  docusaurus-docs/package.json
  docusaurus-docs/sidebarsCommunity.js
  docusaurus-docs/sidebarsCondaStore.js
  docusaurus-docs/sidebarsCondaStoreUI.js
  docusaurus-docs/sidebarsJupyterLab.js
  docusaurus-docs/src/css/custom.css
  docusaurus-docs/src/pages/index.js
  docusaurus-docs/src/pages/index.module.css
Labels: area: documentation 📖, needs: review 👀, type: maintenance 🛠, area: javascript

#1069 Fix conda store server deps
  conda-store-server/pyproject.toml
  recipe/meta.yaml
Labels: area: dependencies 📦, needs: review 👀, type: maintenance 🛠

#1061 [MAINT] Deprecate `/api/v1/environments/`
  conda-store-server/conda_store_server/_internal/server/app.py
  conda-store-server/conda_store_server/_internal/server/views/api.py
  conda-store-server/conda_store_server/_internal/server/views/registry.py
  conda-store-server/tests/_internal/server/views/test_api.py
Labels: area: api 🌐, status: in progress 🏗, needs: review 👀, type: deprecations ⛔️

#1052 Mount code into docker container
  docker-compose.yaml
Labels: needs: review 👀

#1086 Re-add docker blob build artifact type
  conda-store-server/conda_store_server/_internal/schema.py
  conda-store-server/tests/_internal/test_schema.py
Labels: type: bug 🐛, needs: review 👀
